import { RightIcon } from "./Icons";

export const LemonWars = [
  {
    Id: 1,
    heading: "Starter",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$2.80",
    para: "Per month",
    button: "Choose this Plan",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    database: "Unlimited Database",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
  {
    Id: 2,
    heading: "Standard",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$4.20",
    para: "Per month",
    button: "Choose this Plan",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    database: "Unlimited Database",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
  {
    Id: 3,
    heading: "Suprem",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$7.00",
    para: "Per month",
    button: "Choose this Plan",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    database: "Unlimited Database",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
];
export const Premium = [
  {
    Id: 1,
    heading: "Starter",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$30.80",
    para: "Per year",
    button: "Choose this Plan",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    database: "Unlimited Database",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
  {
    Id: 2,
    heading: "Standard",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$40.20",
    para: "Per year",
    button: "Choose this Plan",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    database: "Unlimited Database",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
  {
    Id: 3,
    heading: "Suprem",
    description:
      "with all your customers via all conversation channels in one central dashboard.",
    pricing: "$80.00",
    para: "Per year",
    button: "Choose this Plan",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    database: "Unlimited Database",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
    freessl: "Free SSL",
    softcolus: "Softaculous",
  },
];
