export const LemonWars = [
  {
    Id: 1,
    heading: "Starter",
    pricing: "$2.80",
    para: "Per month",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
  },
  {
    Id: 2,
    heading: "Standard",
    pricing: "$4.20",
    para: "Per month",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
  },
  {
    Id: 3,
    heading: "Suprem",
    pricing: "$7.00",
    para: "Per month",
    subtitle: "2GB SSD",
    bandwidth: "10GB Bandwidth",
    accounts: "15 Email Accounts",
    subdomain: "4 Subdomains",
    parkdomain: "1 Parked Domain",
    websites: "2 Websites",
  },
];
export const Premium = [
  {
    Id: 1,
    heading: "Starter",
    pricing: "$30.80",
    para: "Per year",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
  },
  {
    Id: 2,
    heading: "Standard",
    pricing: "$40.20",
    para: "Per year",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
  },
  {
    Id: 3,
    heading: "Suprem",
    pricing: "$80.00",
    para: "Per year",
    subtitle: "30GB SSD",
    bandwidth: "60GB Bandwidth",
    accounts: "25 Email Accounts",
    subdomain: "9 Subdomains",
    parkdomain: "12 Parked Domain",
    websites: "30 Websites",
  },
];
